name: Publish Blog Posts

on:
  push:
    branches:
      - main
    paths:
      - "posts/dev.to/**.md"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            posts/dev.to/**.md

      - name: Debug changed files
        run: echo "${{ steps.changes.outputs.all_changed_files }}"

      # Dev.to publishing (only changed files)
      - name: Publish to Dev.to
        if: contains(steps.changes.outputs.all_changed_files, 'posts/dev.to/')
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ steps.changes.outputs.all_changed_files }}
          branch: main
