name: Publish to Hashnode
on:
  push:
    branches:
      - main
    paths:
      - "posts/hashnode/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Symlink posts directory
        run: |
          ln -s ${{ github.workspace }}/posts/hashnode /home/runner/work/_actions/PritishMishraa/hashnode-publish-action/v1.0.2/posts/hashnode

      - name: Publish to Hashnode
        uses: PritishMishraa/hashnode-publish-action@v1.0.2
        with:
          src: posts/hashnode
          HASHNODE_PAT: ${{ secrets.HASHNODE_PAT }}
