name: Publish to Hashnode

on:
  push:
    branches: [main]
    paths: ["posts/**/*.md"] # Only run when markdown files in posts/ change

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to Hashnode
        uses: kodelint/publish-to-hashnode@v1.0.1
        with:
          src: "./posts"
          hashnode_pat: ${{ secrets.HASHNODE_PAT }}
          publication_id: ${{ secrets.HASHNODE_PUBLICATION_ID }}
          post_status: "public"
          update_existing_posts: "true"
