name: publish-to-medium
on:
  push:
    paths:
      - medium/**

jobs:
  build:
    name: publish-to-medium
    runs-on: ubuntu-latest
    steps:
    - uses: jitterbit/get-changed-files@v1
    - name: Detecting posts from the changes
      run: |
        i=0
        for changed_file in ${{ steps.files.outputs.added_modified }}; do
          echo "Do something with ${changed_file}."
          if [[ "${changed_file}" == "medium/"* ]];
          then
            echo "File ${changed_file} matched post."
            echo "::set-output name=post${i}::${changed_file}"
            ((i=i+1))
          fi
        done
    - if: steps.posts.outputs.post0
      name: Publish to medium
      uses: infraway/post-medium-action@v1.5.0
      with:
        access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
        markdown_file: ${{ steps.posts.outputs.post0 }}
        base_url: https://medium.com/@email2sroy
        post_url: https://medium.com/@email2sroy
        post_status: draft
