name: Publish Blog Posts

on:
  push:
    branches:
      - main
    paths:
      - "posts/dev.to/**.md"
      - "posts/hashnode/**.md"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            posts/dev.to/**.md
            posts/hashnode/**.md

      - name: Show changed files (debug)
        run: echo "${{ steps.changes.outputs.all_changed_files }}"

      # Publish to Dev.to
      - name: Publish to Dev.to
        if: contains(steps.changes.outputs.all_changed_files, 'posts/dev.to/')
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            posts/dev.to/**/*.md
          branch: main

      # Publish to Hashnode
      - name: Publish to Hashnode
        if: contains(steps.changes.outputs.all_changed_files, 'posts/hashnode/')
        uses: PritishMishraa/hashnode-publish-action@v1.0.2
        with:
          src: posts/hashnode
          HASHNODE_PAT: ${{ secrets.HASHNODE_PAT }}
